In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\user\Desktop\icu_mortality_project\data\processed\modeling_table.csv")

In [3]:
df.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los,gender,anchor_age,...,Glucose_mean_value,Hemoglobin_mean_value,Lactate_mean_value,White Blood Cells_mean_value,Creatinine_max_value,Glucose_max_value,Hemoglobin_max_value,Lactate_max_value,White Blood Cells_max_value,mortality
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266,F,52,...,111.0,11.900000,NaN,4.100000,0.5,115.0,11.9,NaN,4.1,0
1,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,F,55,...,113.0,11.200000,NaN,19.000000,0.4,113.0,11.2,NaN,19.0,0
2,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,F,46,...,149.0,13.250000,NaN,18.550000,0.8,152.0,13.9,NaN,20.1,0
3,10002428,28662225,33987268,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2156-04-12 16:24:18,2156-04-17 15:57:08,4.981134,F,80,...,123.5,9.750000,1.825000,25.150000,0.9,148.0,10.2,2.4,27.9,0
4,10002495,24982426,36753294,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2141-05-22 20:18:01,2141-05-27 22:24:02,5.087512,M,81,...,290.0,13.766667,3.666667,31.533333,1.6,331.0,14.3,4.4,36.8,0

Inspecting Missing Data

In [4]:
missing_pct = df.isna().mean().sort_values(ascending=False)

In [5]:
missing_pct.head(15)

Lactate_mean_value        0.38
Lactate_max_value         0.38
temperature_mean_value    0.11
temperature_min_value     0.11
temperature_max_value     0.11
temperature_last_value    0.11
dbp_max_value             0.09
sbp_mean_value            0.09
dbp_mean_value            0.09
sbp_min_value             0.09
dbp_min_value             0.09
sbp_max_value             0.09
dbp_last_value            0.09
sbp_last_value            0.09
Hemoglobin_mean_value     0.02
dtype: float64

Dropping Features that are too missing

In [6]:
df.shape

(100, 45)

In [7]:
y = df["mortality"]

In [8]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Name: mortality, Length: 100, dtype: int64

In [9]:
df.columns

Index(['subject_id', 'hadm_id', 'stay_id', 'first_careunit', 'last_careunit',
       'intime', 'outtime', 'los', 'gender', 'anchor_age', 'dbp_mean_value',
       'heart_rate_mean_value', 'resp_rate_mean_value', 'sbp_mean_value',
       'spo2_mean_value', 'temperature_mean_value', 'dbp_min_value',
       'heart_rate_min_value', 'resp_rate_min_value', 'sbp_min_value',
       'spo2_min_value', 'temperature_min_value', 'dbp_max_value',
       'heart_rate_max_value', 'resp_rate_max_value', 'sbp_max_value',
       'spo2_max_value', 'temperature_max_value', 'dbp_last_value',
       'heart_rate_last_value', 'resp_rate_last_value', 'sbp_last_value',
       'spo2_last_value', 'temperature_last_value', 'Creatinine_mean_value',
       'Glucose_mean_value', 'Hemoglobin_mean_value', 'Lactate_mean_value',
       'White Blood Cells_mean_value', 'Creatinine_max_value',
       'Glucose_max_value', 'Hemoglobin_max_value', 'Lactate_max_value',
       'White Blood Cells_max_value', 'mortality'],
      dtype='object')

In [10]:
X = df.drop(columns=[
    'mortality','subject_id', 'hadm_id','stay_id','intime','outtime','los'
])

In [11]:
X

,first_careunit,last_careunit,gender,anchor_age,dbp_mean_value,heart_rate_mean_value,resp_rate_mean_value,sbp_mean_value,spo2_mean_value,temperature_mean_value,...,Creatinine_mean_value,Glucose_mean_value,Hemoglobin_mean_value,Lactate_mean_value,White Blood Cells_mean_value,Creatinine_max_value,Glucose_max_value,Hemoglobin_max_value,Lactate_max_value,White Blood Cells_max_value
0,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),F,52,54.100000,96.500000,20.700000,88.900000,96.300000,98.966667,...,0.450000,111.000000,11.900000,NaN,4.100000,0.5,115.0,11.9,NaN,4.1
1,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),F,55,80.960000,93.200000,21.320000,135.320000,96.080000,99.062500,...,0.400000,113.000000,11.200000,NaN,19.000000,0.4,113.0,11.2,NaN,19.0
2,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),F,46,59.840000,79.480000,17.360000,97.760000,98.125000,97.800000,...,0.800000,149.000000,13.250000,NaN,18.550000,0.8,152.0,13.9,NaN,20.1
3,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),F,80,51.918367,110.387755,24.448980,95.285714,97.469388,100.300000,...,0.850000,123.500000,9.750000,1.825000,25.150000,0.9,148.0,10.2,2.4,27.9
4,Coronary Care Unit (CCU),Coronary Care Unit (CCU),M,81,56.648649,106.351351,21.710526,97.783784,97.378378,98.350000,...,1.533333,290.000000,13.766667,3.666667,31.533333,1.6,331.0,14.3,4.4,36.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Coronary Care Unit (CCU),Coronary Care Unit (CCU),M,45,67.727273,110.960000,20.760000,107.409091,97.000000,99.650000,...,0.866667,89.200000,9.533333,1.233333,10.400000,0.9,121.0,9.8,1.6,11.5
96,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),F,46,63.000000,80.000000,21.029412,91.633333,98.000000,97.900000,...,1.940000,232.400000,10.300000,4.500000,11.500000,2.2,315.0,10.7,7.2,13.7
97,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),F,57,NaN,96.434783,25.956522,NaN,96.521739,99.928571,...,0.633333,133.666667,11.850000,NaN,13.800000,0.7,176.0,12.1,NaN,15.3
98,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),F,67,90.000000,94.600000,16.666667,141.000000,94.586207,98.883333,...,0.900000,137.000000,10.900000,NaN,8.500000,0.9,137.0,10.9,NaN,8.5
99,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),F,64,62.914286,82.583333,16.666667,100.828571,95.411765,98.062500,...,2.033333,234.333333,9.350000,2.160000,11.375000,2.2,280.0,10.2,2.7,14.9

Encoding Categorical Variables

In [12]:
X["gender"] = X["gender"].map({'M': 1, 'F':0})

In [13]:
X

,first_careunit,last_careunit,gender,anchor_age,dbp_mean_value,heart_rate_mean_value,resp_rate_mean_value,sbp_mean_value,spo2_mean_value,temperature_mean_value,...,Creatinine_mean_value,Glucose_mean_value,Hemoglobin_mean_value,Lactate_mean_value,White Blood Cells_mean_value,Creatinine_max_value,Glucose_max_value,Hemoglobin_max_value,Lactate_max_value,White Blood Cells_max_value
0,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),0,52,54.100000,96.500000,20.700000,88.900000,96.300000,98.966667,...,0.450000,111.000000,11.900000,NaN,4.100000,0.5,115.0,11.9,NaN,4.1
1,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),0,55,80.960000,93.200000,21.320000,135.320000,96.080000,99.062500,...,0.400000,113.000000,11.200000,NaN,19.000000,0.4,113.0,11.2,NaN,19.0
2,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),0,46,59.840000,79.480000,17.360000,97.760000,98.125000,97.800000,...,0.800000,149.000000,13.250000,NaN,18.550000,0.8,152.0,13.9,NaN,20.1
3,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),0,80,51.918367,110.387755,24.448980,95.285714,97.469388,100.300000,...,0.850000,123.500000,9.750000,1.825000,25.150000,0.9,148.0,10.2,2.4,27.9
4,Coronary Care Unit (CCU),Coronary Care Unit (CCU),1,81,56.648649,106.351351,21.710526,97.783784,97.378378,98.350000,...,1.533333,290.000000,13.766667,3.666667,31.533333,1.6,331.0,14.3,4.4,36.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Coronary Care Unit (CCU),Coronary Care Unit (CCU),1,45,67.727273,110.960000,20.760000,107.409091,97.000000,99.650000,...,0.866667,89.200000,9.533333,1.233333,10.400000,0.9,121.0,9.8,1.6,11.5
96,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),0,46,63.000000,80.000000,21.029412,91.633333,98.000000,97.900000,...,1.940000,232.400000,10.300000,4.500000,11.500000,2.2,315.0,10.7,7.2,13.7
97,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),0,57,NaN,96.434783,25.956522,NaN,96.521739,99.928571,...,0.633333,133.666667,11.850000,NaN,13.800000,0.7,176.0,12.1,NaN,15.3
98,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),0,67,90.000000,94.600000,16.666667,141.000000,94.586207,98.883333,...,0.900000,137.000000,10.900000,NaN,8.500000,0.9,137.0,10.9,NaN,8.5
99,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),0,64,62.914286,82.583333,16.666667,100.828571,95.411765,98.062500,...,2.033333,234.333333,9.350000,2.160000,11.375000,2.2,280.0,10.2,2.7,14.9

In [14]:

X["first_careunit"].value_counts().sort_index()

first_careunit
Cardiac Vascular Intensive Care Unit (CVICU)        25
Coronary Care Unit (CCU)                             8
Medical Intensive Care Unit (MICU)                  18
Medical/Surgical Intensive Care Unit (MICU/SICU)    13
Neuro Stepdown                                       1
Neuro Surgical Intensive Care Unit (Neuro SICU)      2
Surgical Intensive Care Unit (SICU)                 21
Trauma SICU (TSICU)                                 12
Name: count, dtype: int64

In [15]:
X = pd.get_dummies(
    X,
    columns=["first_careunit"],
    drop_first=True
)

In [16]:
X = X.drop(columns=['last_careunit'])

In [17]:
X

,gender,anchor_age,dbp_mean_value,heart_rate_mean_value,resp_rate_mean_value,sbp_mean_value,spo2_mean_value,temperature_mean_value,dbp_min_value,heart_rate_min_value,...,Hemoglobin_max_value,Lactate_max_value,White Blood Cells_max_value,first_careunit_Coronary Care Unit (CCU),first_careunit_Medical Intensive Care Unit (MICU),first_careunit_Medical/Surgical Intensive Care Unit (MICU/SICU),first_careunit_Neuro Stepdown,first_careunit_Neuro Surgical Intensive Care Unit (Neuro SICU),first_careunit_Surgical Intensive Care Unit (SICU),first_careunit_Trauma SICU (TSICU)
0,0,52,54.100000,96.500000,20.700000,88.900000,96.300000,98.966667,41.0,91.0,...,11.9,NaN,4.1,False,True,False,False,False,False,False
1,0,55,80.960000,93.200000,21.320000,135.320000,96.080000,99.062500,67.0,78.0,...,11.2,NaN,19.0,False,False,False,False,False,True,False
2,0,46,59.840000,79.480000,17.360000,97.760000,98.125000,97.800000,45.0,55.0,...,13.9,NaN,20.1,False,False,True,False,False,False,False
3,0,80,51.918367,110.387755,24.448980,95.285714,97.469388,100.300000,19.0,100.0,...,10.2,2.4,27.9,False,True,False,False,False,False,False
4,1,81,56.648649,106.351351,21.710526,97.783784,97.378378,98.350000,40.0,83.0,...,14.3,4.4,36.8,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,45,67.727273,110.960000,20.760000,107.409091,97.000000,99.650000,55.0,29.0,...,9.8,1.6,11.5,True,False,False,False,False,False,False
96,0,46,63.000000,80.000000,21.029412,91.633333,98.000000,97.900000,43.0,65.0,...,10.7,7.2,13.7,False,False,True,False,False,False,False
97,0,57,NaN,96.434783,25.956522,NaN,96.521739,99.928571,NaN,85.0,...,12.1,NaN,15.3,False,False,False,False,False,True,False
98,0,67,90.000000,94.600000,16.666667,141.000000,94.586207,98.883333,75.0,86.0,...,10.9,NaN,8.5,False,False,False,False,False,True,False
99,0,64,62.914286,82.583333,16.666667,100.828571,95.411765,98.062500,36.0,71.0,...,10.2,2.7,14.9,False,False,False,False,False,True,False

Impute missing values

In [18]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')
X_imputed = imputer.fit_transform(X)

In [19]:
X_imputed

array([[ 0.        , 52.        , 54.1       , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , 55.        , 80.96      , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 46.        , 59.84      , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        , 57.        , 63.75      , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 67.        , 90.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 64.        , 62.91428571, ...,  0.        ,
         1.        ,  0.        ]], shape=(100, 43))

In [20]:
X_imputed

array([[ 0.        , 52.        , 54.1       , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        , 55.        , 80.96      , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 46.        , 59.84      , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.        , 57.        , 63.75      , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 67.        , 90.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.        , 64.        , 62.91428571, ...,  0.        ,
         1.        ,  0.        ]], shape=(100, 43))

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_imputed,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [22]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [23]:
from sklearn.metrics import roc_auc_score

y_pred_proba = model.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_pred_proba)

print("Baseline AUC:", auc)

Baseline AUC: 0.4444444444444444

In [24]:
model.classes_

array([0, 1])

In [25]:
X.shape

(100, 43)

In [26]:
y_test.value_counts(normalize=True)

mortality
0    0.9
1    0.1
Name: proportion, dtype: float64

In [27]:
X.corrwith(y_train)

gender                                                             0.146044
anchor_age                                                         0.135419
dbp_mean_value                                                    -0.015434
heart_rate_mean_value                                              0.267765
resp_rate_mean_value                                               0.273518
sbp_mean_value                                                    -0.024612
spo2_mean_value                                                    0.050287
temperature_mean_value                                            -0.067094
dbp_min_value                                                     -0.080978
heart_rate_min_value                                               0.179905
resp_rate_min_value                                                0.102367
sbp_min_value                                                     -0.090791
spo2_min_value                                                    -0.162402
temperature_min_value                                             -0.162075
dbp_max_value                                                      0.051935
heart_rate_max_value                                               0.265826
resp_rate_max_value                                                0.171498
sbp_max_value                                                      0.149578
spo2_max_value                                                     0.122904
temperature_max_value                                             -0.081947
dbp_last_value                                                     0.008858
heart_rate_last_value                                              0.075250
resp_rate_last_value                                              -0.103961
sbp_last_value                                                    -0.069289
spo2_last_value                                                    0.255646
temperature_last_value                                            -0.013199
Creatinine_mean_value                                              0.357974
Glucose_mean_value                                                 0.020341
Hemoglobin_mean_value                                             -0.155706
Lactate_mean_value                                                 0.428943
White Blood Cells_mean_value                                      -0.037891
Creatinine_max_value                                               0.393030
Glucose_max_value                                                 -0.015188
Hemoglobin_max_value                                              -0.186659
Lactate_max_value                                                  0.395127
White Blood Cells_max_value                                        0.036653
first_careunit_Coronary Care Unit (CCU)                            0.199005
first_careunit_Medical Intensive Care Unit (MICU)                  0.217577
first_careunit_Medical/Surgical Intensive Care Unit (MICU/SICU)   -0.027282
first_careunit_Neuro Stepdown                                     -0.040057
first_careunit_Neuro Surgical Intensive Care Unit (Neuro SICU)    -0.040057
first_careunit_Surgical Intensive Care Unit (SICU)                -0.069680
first_careunit_Trauma SICU (TSICU)                                -0.001565
dtype: float64

In [28]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
model.fit(X_train, y_train)

y_pred_proba = model.predict_proba(X_test)[:, 1]
auc = roc_auc_score(y_test, y_pred_proba)
print("Improved AUC:", auc)

Improved AUC: 0.5277777777777778

In [29]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=5, scoring='roc_auc')
print("CV AUC:", scores.mean())

CV AUC: 0.6690476190476191

In [30]:
print(model.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': 'balanced', 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'monotonic_cst': None, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

In [31]:
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': 'balanced',
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [36]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 5, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', None]
}

rf = RandomForestClassifier(random_state=42)

In [37]:
grid_rf = GridSearchCV(
    rf,
    param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10],
                         'max_features': ['sqrt', 'log2', None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='roc_auc')

In [38]:
print("Best CV AUC:", grid_rf.best_score_)
print("Best Parameters:", grid_rf.best_params_)

Best CV AUC: 0.7807142857142857
Best Parameters: {'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}

Trainning the final Random Forest Using the best parameters.

In [39]:
best_params = grid_rf.best_params_

final_rf = RandomForestClassifier(
    **best_params,
    random_state=24
)

final_rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=24)

In [49]:
from sklearn.metrics import roc_auc_score

y_pred_proba = final_rf.predict_proba(X_test)[:,1]
auc_test = roc_auc_score(y_test, y_pred_proba)
print("Test set AUC:", auc_test)

Test set AUC: 0.2222222222222222

In [46]:
import numpy as np
assert X_train.shape[0] == len(y_train)
assert X_test.shape[0] == len(y_test)
print(X_train.head())
print(y_train.head())

AttributeError: 'numpy.ndarray' object has no attribute 'head'